### PR TITLE
removing unnecessary return

### PR DESCRIPTION
**Pull request by unlucio**
removing an unnecessary return that would make jest go bonk if you're using jest for tests, d'oh!

### CODE REVIEW

**Comment by unlucio** [comment]
@odino u use jest bro?

**Comment by hossam-fares** [comment]
@unlucio ciao amigo, how are you?

**Comment by unlucio** [comment]
hello @hossam-fares big daddy, I'm back and spreading these tools ;)

**Comment by odino** [comment]
@unlucio hello :) not really, but thanks for the cleanup! :)

**Comment by odino** [comment]
in `1.1.1`!

**Comment by odino** [comment]
3m -- we established a new record :smile:

**Pull request merged**
